# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Pods for HARU
def requirePods
  pod 'AFDateHelper'
  pod 'DropDown'
  pod 'FSCalendar'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end

target 'HARU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  requirePods
end

#target 'HARUTests' do
#    inherit! :search_paths
#    requirePods
#end
#
#target 'HARUUITests' do
#  inherit! :search_paths
#  requirePods
#  # P ods for testing
#end
